#image: nvidia/cuda:9.0-devel
image: ubuntu-cpp

stages:
  - build

build_linux_gcc:
  stage: build
  tags:
    - linux
    - g++
  script:
    - mkdir -p build_gcc
    - cd build_gcc
    - cmake .. -DCMAKE_CXX_COMPILER=g++ -DSUPRA_DEVICE_CEPHASONICS=OFF -DSUPRA_DEVICE_ULTRASONIX=OFF -DSUPRA_DOWNLOAD_SAMPLEDATA=OFF -DSUPRA_USE_CAMPVIS=OFF -DSUPRA_PROFILING=OFF -DSUPRA_INTERFACE_ROS=OFF
    - make
  cache:
    key: build_cache_gcc
    paths:
      - build_gcc/
  artifacts:
    paths:
    - build_gcc/